repos:
  - repo: https://github.com/ambv/black
    rev: 24.2.0
    hooks:
      - id: black
        language_version: python3.10
        args: [ --line-length=120 ]
        exclude: 'tests|scripts'

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
      - id: flake8
        language_version: python3.10
        args: [ --config=.flake8 ]
        exclude: 'tests|scripts'
      - id: check-added-large-files
        args: [ '--maxkb=123' ]
      - id: trailing-whitespace

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: [ "--profile", "black", "--filter-files", "--line-length", "100" ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        args: [ "--ignore-missing-imports", "--namespace-packages", "--explicit-package-bases" ]
        additional_dependencies: [ 'types-requests' ]