name: python_format_check

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  format-check:
    name: Check python code formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install black flake8 mypy types-requests

      - name: Formats code
        run: black .

      - name: Lints code for PEP 8 compliance
        run: flake8 .

      - name: Perform Scan
        uses: ShiftLeftSecurity/scan-action@master
        with:
          type: "python"

#      - name: Performs static type checking
#        run: mypy . --ignore-missing-imports --namespace-packages --explicit-package-bases